version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  
    environment:
      MYSQL_HOST: mydb.ctmngrvsqywk.ap-south-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydatabase
      MYSQL_PASSWORD: data1234
    volumes:
      - db_data:/var/lib/mysql  
        # command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
